language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U conan
  - pip install codecov
  - export PYPHYSX_COV=true
install:
  - python setup.py build
#  - pip install ".[test]" .
script:
  - cd build/temp.linux-x86_64-3.7
  - pytest tests
  - make gcov
after_success:
  - codecov -X gcov
